server:
  port: 9191

spring:
  cloud:
    gateway:
      routes:
        - id: workshop-product-service
          uri: http://localhost:9001
          predicates:
            - Path=/products/**
        - id: workshop-shopping-cart-service
          uri: http://localhost:9002
          predicates:
            - Path=/carts/**

eureka:
  instance:
    hostname: localhost
    port: 8761
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/